title:               "凡人牧白's Blog"
tagline:             'Personal Blog'
description:         "凡人牧白's Blog"
url:                 http://ly95.me
baseurl:             '/'
permalink:           /:year-:month-:day/:slug.html

paginate:            1
paginate_path:       /page/:num

author:
  name:              Yang Lin
  url:               http://github.com/ly95
  email:             linyang95@aol.com

collections:
  - my_tags

jekyll-archives:
  enabled:
    - year
    - tags
  layouts:
    year:            'year-archive'
    tag:             'tag-archive'
  permalinks:
    year:            '/:year/'
    month:           '/:year/:month/'
    day:             '/:year/:month/:day/'
    tag:             '/tag/:name/'
    category:        '/category/:name/'

exclude:
  - LICENSE
  - README.md
  - tags.py
  - tags.php

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
